GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJuYW1lIjoiQW5pZXMgQUkgZW50cmVwZW5ldXIiLCJlbWFpbCI6ImFuaXNAZ21haWwuY29tIiwiZGVzY3JpcHRpb24iOiJWUCBUZWtub21hZHlhIiwiaWF0IjoxNzI0MjA3ODM2LCJleHAiOjE3MjQyMDc4NTZ9.CmqEe3NWz3YP0GS75-Jf1-mgqDVnThzcZzMdMMAMwAs


###

POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Adam Schewneger",
    "email": "adam@gmail.com",
    "description": "Intern Teknomadya",
    "password": "123",
    "confPassword": "123"
}


###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "anis@gmail.com",
    "password": "123"
}

###

GET http://localhost:5000/token

###

DELETE http://localhost:5000/logout